{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Restaurant Review API",
    "description" : "Restaurant Review Application built by Racheal",
    "contact" : {
      "name" : "Racheal Kuranchie",
      "url" : "https://linktr.ee/rachealkuranchie"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "tags" : [ {
    "name" : "Diner",
    "description" : "Everything about your Restaurants"
  }, {
    "name" : "User",
    "description" : "Everything about your Users"
  }, {
    "name" : "Review",
    "description" : "Everything about your User's Reviews"
  }, {
    "name" : "Favorite",
    "description" : "Everything about your User's Reviews"
  } ],
  "paths" : {
    "/diners" : {
      "description" : "Restaurant resource",
      "get" : {
        "tags" : [ "Diner" ],
        "description" : "Operation to fetch all restaurant data",
        "parameters" : [ {
          "name" : "restaurant_id",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/inline_response_200"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "Diner" ],
        "description" : "Operation to add a new restaurant data",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/diners_body"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Record successfully added"
          }
        }
      }
    },
    "/diners{id}" : {
      "description" : "Restaurant resource",
      "get" : {
        "tags" : [ "Diner" ],
        "description" : "Operation to fetch a restaurant data",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/inline_response_200"
                  }
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "Diner" ],
        "description" : "Operation to update restaurant data",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/dinersid_body"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Record successfully updated"
          }
        }
      },
      "delete" : {
        "tags" : [ "Diner" ],
        "description" : "Operation to delete restaurant data",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Record successfully deleted"
          }
        }
      }
    },
    "/diner" : {
      "description" : "Restaurant Search Resource",
      "get" : {
        "tags" : [ "Diner" ],
        "description" : "Operation to search a restaurant with name or location",
        "parameters" : [ {
          "name" : "search",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "mix"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/inline_response_200"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/signup" : {
      "description" : "Users resource",
      "post" : {
        "tags" : [ "User" ],
        "description" : "Operation to add a users data",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/users_signup_body"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Record successfully added"
          }
        }
      }
    },
    "/users/login" : {
      "description" : "Users resource",
      "post" : {
        "tags" : [ "User" ],
        "description" : "Operation to log a user to the app",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/users_login_body"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "User has been successfully loggedin"
          },
          "400" : {
            "description" : "Invalid username/password supplied"
          }
        }
      }
    },
    "/user/logout" : {
      "description" : "User Logout",
      "get" : {
        "tags" : [ "User" ],
        "description" : "Operation to logout a user",
        "parameters" : [ {
          "name" : "user_id",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Response"
          }
        }
      }
    },
    "/user" : {
      "description" : "User resource",
      "get" : {
        "tags" : [ "User" ],
        "description" : "Operation to fetch a user with their reviews and favorites",
        "parameters" : [ {
          "name" : "restaurant_id",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/inline_response_200_1"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reviews" : {
      "description" : "Reviews resource",
      "put" : {
        "tags" : [ "Review" ],
        "description" : "Operation to update a users review to a restaurant",
        "parameters" : [ {
          "name" : "review_id",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/reviews_body"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Record successfully updated"
          }
        }
      },
      "post" : {
        "tags" : [ "Review" ],
        "description" : "Operation to add a users review to a restaurant",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/reviews_body_1"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Record successfully added"
          }
        }
      },
      "delete" : {
        "tags" : [ "Review" ],
        "description" : "Operation to delete a Review",
        "parameters" : [ {
          "name" : "review_id",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Record successfully deleted"
          }
        }
      }
    },
    "/favorites" : {
      "description" : "Favorite resource",
      "post" : {
        "tags" : [ "Favorite" ],
        "description" : "Operation to add a restaurant as favorite",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/favorites_body"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Record successfully added"
          }
        }
      },
      "delete" : {
        "tags" : [ "Favorite" ],
        "description" : "Operation to delete a Review",
        "parameters" : [ {
          "name" : "favorite_id",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "example" : 1
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Record successfully deleted"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "inline_response_200" : {
        "properties" : {
          "Restaurant ID" : {
            "type" : "integer",
            "example" : 1
          },
          "name" : {
            "type" : "string",
            "example" : "The mix restaurant"
          },
          "contact" : {
            "type" : "string",
            "example" : "542802959"
          },
          "website_url" : {
            "type" : "string",
            "example" : "www.excober.com"
          },
          "location" : {
            "type" : "string",
            "example" : "East Legon"
          },
          "average_ratings" : {
            "type" : "integer",
            "example" : 0
          },
          "category" : {
            "type" : "string",
            "example" : "All"
          },
          "working_hours" : {
            "type" : "string"
          },
          "about" : {
            "type" : "string",
            "example" : "Come and have an experience"
          },
          "profile image" : {
            "type" : "string",
            "example" : "/storage/2108985171.jpg"
          },
          "imagesss" : {
            "type" : "string",
            "example" : "[\"/storage/773438779.jpg\\\"\",\"/storage/441606909.jpg\\\"\"]"
          },
          "reviews" : {
            "type" : "array",
            "example" : [ ]
          }
        }
      },
      "diners_body" : {
        "type" : "object",
        "properties" : {
          "Restaurant ID" : {
            "type" : "integer",
            "example" : 1
          },
          "name" : {
            "type" : "string",
            "example" : "The mix restaurant"
          },
          "contact" : {
            "type" : "string",
            "example" : "542802959"
          },
          "website_url" : {
            "type" : "string",
            "example" : "www.excober.com"
          },
          "location" : {
            "type" : "string",
            "example" : "East Legon"
          },
          "average_ratings" : {
            "type" : "integer",
            "example" : 0
          },
          "category" : {
            "type" : "string",
            "example" : "All"
          },
          "working_hours" : {
            "type" : "string"
          },
          "about" : {
            "type" : "string",
            "example" : "Come and have an experience"
          },
          "profile image" : {
            "type" : "string",
            "example" : "/storage/2108985171.jpg"
          },
          "imagesss" : {
            "type" : "string",
            "example" : "[\"/storage/773438779.jpg\\\"\",\"/storage/441606909.jpg\\\"\"]"
          }
        }
      },
      "dinersid_body" : {
        "type" : "object",
        "properties" : {
          "Restaurant ID" : {
            "type" : "integer",
            "example" : 1
          },
          "name" : {
            "type" : "string",
            "example" : "The mix restaurant"
          },
          "contact" : {
            "type" : "string",
            "example" : "542802959"
          },
          "website_url" : {
            "type" : "string",
            "example" : "www.excober.com"
          },
          "location" : {
            "type" : "string",
            "example" : "East Legon"
          },
          "average_ratings" : {
            "type" : "integer",
            "example" : 0
          },
          "category" : {
            "type" : "string",
            "example" : "All"
          },
          "working_hours" : {
            "type" : "string"
          },
          "about" : {
            "type" : "string",
            "example" : "Come and have an experience"
          },
          "profile image" : {
            "type" : "string",
            "example" : "/storage/2108985171.jpg"
          },
          "imagesss" : {
            "type" : "string",
            "example" : "[\"/storage/773438779.jpg\\\"\",\"/storage/441606909.jpg\\\"\"]"
          }
        }
      },
      "users_signup_body" : {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "example" : "John Doe"
          },
          "username" : {
            "type" : "string",
            "example" : "john2020"
          },
          "email" : {
            "type" : "string",
            "example" : "johndoe@gmail.com"
          },
          "password" : {
            "type" : "string",
            "example" : "password123"
          },
          "confirm password" : {
            "type" : "string",
            "example" : "password123"
          }
        }
      },
      "users_login_body" : {
        "type" : "object",
        "properties" : {
          "email" : {
            "type" : "string",
            "example" : "johndoe@gmail.com"
          },
          "password" : {
            "type" : "string",
            "example" : "password123"
          }
        }
      },
      "inline_response_200_1" : {
        "properties" : {
          "User_id" : {
            "type" : "integer",
            "example" : 1
          },
          "name" : {
            "type" : "string",
            "example" : "John Doe"
          },
          "username" : {
            "type" : "string",
            "example" : "john2020"
          },
          "email" : {
            "type" : "string",
            "example" : "johndoe@gmail.com"
          },
          "reviews" : {
            "type" : "array",
            "example" : [ ]
          },
          "favorites" : {
            "type" : "array",
            "example" : [ ]
          }
        }
      },
      "reviews_body" : {
        "type" : "object",
        "properties" : {
          "coment" : {
            "type" : "string",
            "example" : "Great food, good customer serviice"
          },
          "ratings" : {
            "type" : "integer",
            "example" : 4
          },
          "restaurant_id" : {
            "type" : "integer",
            "example" : 1
          }
        }
      },
      "reviews_body_1" : {
        "type" : "object",
        "properties" : {
          "coment" : {
            "type" : "string",
            "example" : "Great food, good customer serviice"
          },
          "ratings" : {
            "type" : "integer",
            "example" : 5
          },
          "restaurant_id" : {
            "type" : "integer",
            "example" : 1
          }
        }
      },
      "favorites_body" : {
        "type" : "object",
        "properties" : {
          "restaurant_id" : {
            "type" : "integer",
            "example" : 1
          }
        }
      }
    }
  }
}